import Provider  from "./provider";
import "./globals.css";
import Header from "@/components/custom/Header";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body 
      >

      <Provider>
        <Header />
        {children}
        </Provider>
      </body>
    </html>
  );
}
