import Provider  from "./provider";
import "./globals.css";
import Header from "@/components/custom/Header";
import ConvexClientProvider from "./ConvexClientProvider";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body 
      >

      <ConvexClientProvider>
      <Provider>
        <Header />
        {children}
        </Provider>
      </ConvexClientProvider>



      </body>
    </html>
  );
}
